/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2021-08-03 06:22:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.common.system.menu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menuManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.0.0.RELEASE.jar", Long.valueOf(1555919658000L));
    _jspx_dependants.put("jar:file:/C:/Winplus_SIS_Workspace8/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Winplus_SIS/WEB-INF/lib/spring-webmvc-5.0.0.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1506564196000L));
    _jspx_dependants.put("jar:file:/C:/Winplus_SIS_Workspace8/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Winplus_SIS/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Winplus_SIS_Workspace8/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Winplus_SIS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1555919670000L));
    _jspx_dependants.put("jar:file:/C:/Winplus_SIS_Workspace8/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Winplus_SIS/WEB-INF/lib/spring-webmvc-5.0.0.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1506564196000L));
    _jspx_dependants.put("/WEB-INF/jsp/common/include/taglib.jspf", Long.valueOf(1577410167197L));
    _jspx_dependants.put("jar:file:/C:/Winplus_SIS_Workspace8/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Winplus_SIS/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n\r\n\r\n");
      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.write("\r\n\r\n\r\n\r\n\r\n");
      out.write("\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/common/include/default_resources_header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/common/include/default_page_script_header.jsp", out, false);
      out.write("\r\n<script type=\"text/javascript\">\r\n\t");
      out.write("\r\n\tvar erpLayout;\r\n\tvar erpRibbon;\r\n\tvar erpTree;\t\r\n\tvar currentErpTreeId;\r\n\tvar cmbUSE_YN;\r\n\tvar cmbFOLDER_YN;\r\n\tvar crud;\r\n\t\r\n\t$(document).ready(function(){\t\t\r\n\t\tinitErpLayout();\r\n\t\tinitErpRibbon();\r\n\t\tinitErpTree();\r\n\t\tinitDhtmlXCombo();\r\n\t\tsearchErpTree();\r\n\t});\r\n\t\r\n\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n\tfunction initErpLayout(){\r\n\t\terpLayout = new dhtmlXLayoutObject({\r\n\t\t\tparent: document.body\r\n\t\t\t, skin : ERP_LAYOUT_CURRENT_SKINS\r\n\t\t\t, pattern: \"3L\"\r\n\t\t\t, cells: [\r\n\t\t\t\t{id: \"a\", text: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuDto.menu_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", header:true, width:300}\r\n\t\t\t\t, {id: \"b\", text: \"\", header:false, fix_size : [true, true]}\r\n\t\t\t\t, {id: \"c\", text: \"\", header:false}\r\n\t\t\t]\t\t\r\n\t\t});\r\n\t\terpLayout.cells(\"a\").attachObject(\"div_erp_tree\");\r\n\t\terpLayout.cells(\"b\").setHeight(ERP_LAYOUT_RIBBON_HEIGHT);\r\n\t\terpLayout.cells(\"b\").attachObject(\"div_erp_ribbon\");\r\n\t\terpLayout.cells(\"c\").attachObject(\"div_erp_contents_wrapper\");\r\n\t\t\r\n\t\terpLayout.setSeparatorSize(1, 0);\r\n\t}\r\n\t");
      out.write("\r\n\t\r\n\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n\tfunction initErpRibbon(){\r\n\t\terpRibbon = new dhtmlXRibbon({\r\n\t\t\tparent : \"div_erp_ribbon\"\r\n\t\t\t, skin : ERP_RIBBON_CURRENT_SKINS\r\n\t\t\t, icons_path : ERP_RIBBON_CURRENT_ICON_PATH\r\n\t\t\t, items : [\r\n\t\t\t\t{type : \"block\", mode : 'rows', list : [\r\n\t\t\t\t\t{id : \"add_data\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/add.gif\", imgdis : \"menu/add_dis.gif\", disable : true}\r\n\t\t\t\t\t, {id : \"delete_data\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/delete.gif\", imgdis : \"menu/delete_dis.gif\", disable : true}\r\n\t\t\t\t\t, {id : \"save_data\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/save.gif\", imgdis : \"menu/save_dis.gif\", disable : true}\r\n\t\t\t\t\t//, {id : \"excel_data\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/excel.gif\", imgdis : \"menu/excel_dis.gif\", disable : true, unused : true}\r\n\t\t\t\t\t//, {id : \"print_data\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f4(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/print.gif\", imgdis : \"menu/print_dis.gif\", disable : true, unused : true}\t\r\n\t\t\t\t]}\t\t\t\t\t\t\t\r\n\t\t\t]\r\n\t\t});\r\n\t\t\r\n\t\terpRibbon.attachEvent(\"onClick\", function(itemId, bId){\r\n\t\t\tif(itemId == \"search_data\"){\r\n\t\t    \t\r\n\t\t    } else if (itemId == \"add_data\"){\r\n\t\t    \taddData();\r\n\t\t    } else if (itemId == \"delete_data\"){\r\n\t\t    \tdeleteData();\r\n\t\t    } else if (itemId == \"save_data\"){\r\n\t\t    \tsaveData();\r\n\t\t    } else if (itemId == \"excel_data\"){\r\n\t\t    \t\r\n\t\t    } else if (itemId == \"print_data\"){\r\n\t\t    \t\r\n\t\t    }\r\n\t\t});\r\n\t}\r\n\t");
      out.write("\r\n\t\r\n\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n\tfunction initErpTree(){\r\n\t\terpTree = new dhtmlXTreeObject({\r\n\t\t\tparent : \"div_erp_tree\"\r\n\t\t\t, skin : ERP_TREE_CURRENT_SKINS\t\t\t\r\n\t\t\t, image_path : ERP_TREE_CURRENT_IMAGE_PATH\r\n\t\t});\r\n\t\terpTree.attachEvent(\"onClick\", function(id){\r\n\t\t\tif(!$erp.isEmpty(id)){\r\n\t\t\t\t");
      out.write("\r\n\t\t\t\tif(id == \"#root\"){\r\n\t\t\t\t\tcrud = null;\r\n\t\t\t\t\tcurrentErpTreeId = null;\r\n\t\t\t\t\t$erp.clearInputInElement(\"tb_erp_data\");\r\n\t\t\t\t\tdocument.getElementById(\"div_data_info\").textContent = '메뉴 등록/수정 대기중';\r\n\t\t\t\t} else {\r\n\t\t\t\t\tcrud = null;\r\n\t\t\t\t\tcurrentErpTreeId = id;\r\n\t\t\t\t\tsearchData();\t\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction searchErpTree(){\r\n\t\terpLayout.progressOn();\r\n\t\t\r\n\t\t$.ajax({\r\n\t\t\turl : \"/common/system/menu/menuManagementR1.do\"\r\n\t\t\t,data : {}\r\n\t\t\t,method : \"POST\"\r\n\t\t\t,dataType : \"JSON\"\r\n\t\t\t,success : function(data){\r\n\t\t\t\terpLayout.progressOff();\r\n\t\t\t\tif(data.isError){\r\n\t\t\t\t\t$erp.ajaxErrorMessage(data);\r\n\t\t\t\t} else {\t\t\t\r\n\t\t\t\t\tvar menuTreeMap = data.menuTreeMap;\r\n\t\t\t\t\tvar menuTreeDataList = menuTreeMap.item;\r\n\t\t\t\t\tif($erp.isEmpty(menuTreeDataList)){\r\n\t\t\t\t\t\t$erp.alertMessage({\r\n\t\t\t\t\t\t\t\"alertMessage\" : \"grid.noSearchData\"\r\n\t\t\t\t\t\t\t, \"alertCode\" : null\r\n\t\t\t\t\t\t\t, \"alertType\" : \"info\"\r\n\t\t\t\t\t\t});\r\n\t\t\t\t\t} else {\r\n\t\t\t\t\t\terpTree.deleteChildItems(0);\r\n\t\t\t\t\t\terpTree.parse(menuTreeMap, 'json');\r\n\t\t\t\t\t\tcrud = null;\r\n\t\t\t\t\t\tcurrentErpTreeId = null;\r\n\t\t\t\t\t\t$erp.clearInputInElement(\"tb_erp_data\");\r\n\t\t\t\t\t\tdocument.getElementById(\"div_data_info\").textContent = '메뉴 등록/수정 대기중';\r\n\t\t\t\t\t\terpTree.openAllItems(\"0\");\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t}, error : function(jqXHR, textStatus, errorThrown){\r\n\t\t\t\terpLayout.progressOff();\r\n\t\t\t\t$erp.ajaxErrorHandler(jqXHR, textStatus, errorThrown);\r\n");
      out.write("\t\t\t}\r\n\t\t});\r\n\t}\r\n\t");
      out.write("\r\n\t\r\n\t");
      out.write("\r\n\t\r\n\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n\tfunction isSearchValidate(){\r\n\t\tvar isValidated = true;\r\n\t\tvar alertMessage = \"\";\r\n\t\tvar alertCode = \"\";\r\n\t\tvar alertType = \"error\";\r\n\t\t\r\n\t\tif($erp.isEmpty(currentErpTreeId)){\r\n\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.noSelectedData\";\r\n\t\t\talertCode = \"-1\";\r\n\t\t}\r\n\t\t\r\n\t\tif(!isValidated){\r\n\t\t\t$erp.alertMessage({\r\n\t\t\t\t\"alertMessage\" : alertMessage\r\n\t\t\t\t, \"alertCode\" : alertCode\r\n\t\t\t\t, \"alertType\" : alertType\r\n\t\t\t});\r\n\t\t}\r\n\t\t\r\n\t\treturn isValidated;\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction searchData(){\r\n\t\tif(!isSearchValidate()) { return false; }\r\n\t\t\r\n\t\terpLayout.progressOn();\r\n\t\t\r\n\t\t$.ajax({\r\n\t\t\turl : \"/common/system/menu/menuManagementR2.do\"\r\n\t\t\t,data : {\r\n\t\t\t\t\"MENU_CD\" : currentErpTreeId\r\n\t\t\t}\r\n\t\t\t,method : \"POST\"\r\n\t\t\t,dataType : \"JSON\"\r\n\t\t\t,success : function(data){\r\n\t\t\t\terpLayout.progressOff();\r\n\t\t\t\tif(data.isError){\r\n\t\t\t\t\t$erp.ajaxErrorMessage(data);\r\n\t\t\t\t} else {\t\t\t\r\n\t\t\t\t\tvar dataMap = data.dataMap;\t\t\t\t\r\n\t\t\t\t\tif($erp.isEmpty(dataMap)){\r\n\t\t\t\t\t\t$erp.alertMessage({\r\n\t\t\t\t\t\t\t\"alertMessage\" : \"grid.noSearchData\"\r\n\t\t\t\t\t\t\t, \"alertCode\" : \"\"\r\n\t\t\t\t\t\t\t, \"alertType\" : \"info\"\r\n\t\t\t\t\t\t});\r\n\t\t\t\t\t} else {\t\t\t\t\t\t\r\n\t\t\t\t\t\tcrud = \"U\";\r\n\t\t\t\t\t\tvar tbErpData = document.getElementById(\"tb_erp_data\");\r\n\t\t\t\t\t\t$erp.clearInputInElement(tbErpData);\r\n\t\t\t\t\t\t$erp.bindTextValue(dataMap, tbErpData);\r\n\t\t\t\t\t\t$erp.bindCmbValue(dataMap, tbErpData);\r\n\t\t\t\t\t\tdocument.getElementById(\"OLD_MENU_NM\").value=document.getElementById(\"txtMENU_NM\").value;\r\n\t\t\t\t\t\tdocument.getElementById(\"div_data_info\").textContent = '메뉴 수정 중';\r\n");
      out.write("\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t}, error : function(jqXHR, textStatus, errorThrown){\r\n\t\t\t\terpLayout.progressOff();\r\n\t\t\t\t$erp.ajaxErrorHandler(jqXHR, textStatus, errorThrown);\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction addData(){\r\n\t\tif(crud != \"C\"){\r\n\t\t\tvar menu_cd = document.getElementById(\"txtMENU_CD\").value;\t\t\r\n\t\t\tvar menu_nm = document.getElementById(\"OLD_MENU_NM\").value;\r\n\r\n\t\t\t$erp.clearInputInElement(\"tb_erp_data\");\r\n\t\t\t\r\n\t\t\tif(!$erp.isEmpty(menu_cd)){\t\t\r\n\t\t\t\tdocument.getElementById(\"txtUPPER_MENU_CD\").value = menu_cd;\r\n\t\t\t\tdocument.getElementById(\"txtUPPER_MENU_NM\").value = menu_nm;\t\t\t\r\n\t\t\t}\r\n\t\t\tcrud = \"C\";\r\n\t\t\tdocument.getElementById(\"div_data_info\").textContent = '메뉴 등록 중';\r\n\t\t}\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction isSaveValidate(){\r\n\t\terpLayout.progressOn();\r\n\t\t\r\n\t\tvar isValidated = true;\r\n\t\tvar alertMessage = \"\";\r\n\t\tvar alertCode = \"\";\r\n\t\tvar alertType = \"error\";\r\n\t\r\n\t\tvar menu_nm = document.getElementById(\"txtMENU_NM\").value;\r\n\t\tvar menu_ordr = document.getElementById(\"txtMENU_ORDR\").value;\r\n\t\tvar use_yn = cmbUSE_YN.getSelectedValue();\r\n\t\tvar folder_yn = cmbFOLDER_YN.getSelectedValue();\r\n\t\t\r\n\t\tif($erp.isEmpty(crud)){\r\n\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.noChanged\";\r\n\t\t\talertCode = \"-1\";\r\n\t\t} else if($erp.isEmpty(menu_nm)){\r\n\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.system.menu.menu_nm.empty\";\r\n\t\t\talertCode = \"-2\";\r\n\t\t} else if($erp.isLengthOver(menu_nm, 50)){ \r\n\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.system.menu.menu_nm.length50Over\";\r\n\t\t\talertCode = \"-3\";\r\n\t\t} else if($erp.isEmpty(menu_ordr) || isNaN(menu_ordr)){\r\n\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.system.menu.menu_ordr.onlyNumber\";\r\n\t\t\talertCode = \"-4\";\r\n\t\t} else if($erp.isEmpty(use_yn)){\r\n");
      out.write("\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.use_yn.empty\";\r\n\t\t\talertCode = \"-5\";\r\n\t\t} else if($erp.isEmpty(folder_yn)){\r\n\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.system.menu.folder_yn.empty\";\r\n\t\t\talertCode = \"-6\";\r\n\t\t}\r\n\t\t\r\n\t\tif(!isValidated){\r\n\t\t\t$erp.alertMessage({\r\n\t\t\t\t\"alertMessage\" : alertMessage\r\n\t\t\t\t, \"alertCode\" : alertCode\r\n\t\t\t\t, \"alertType\" : alertType\r\n\t\t\t});\r\n\t\t}\r\n\t\t\r\n\t\treturn isValidated;\r\n\t}\r\n\t\r\n\tfunction isDeleteValidate(){\r\n\t\tvar isValidated = true;\r\n\t\tvar alertMessage = \"\";\r\n\t\tvar alertCode = \"\";\r\n\t\tvar alertType = \"error\";\r\n\t\t\r\n\t\tvar menu_cd = document.getElementById(\"txtMENU_CD\").value;\r\n\t\tvar lower_menu_cd = erpTree.getSubItems(menu_cd);\t\t\r\n\t\t\r\n\t\tif($erp.isEmpty(menu_cd)){\r\n\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.noSelectedData\";\r\n\t\t\talertCode = \"-1\";\r\n\t\t}else if(!$erp.isEmpty(lower_menu_cd)){\r\n\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.system.menu.no_delete_contain_submenus\";\r\n\t\t\talertCode = \"-1\";\r\n\t\t}\t\t\r\n\t\t\r\n\t\tif(!isValidated){\r\n");
      out.write("\t\t\t$erp.alertMessage({\r\n\t\t\t\t\"alertMessage\" : alertMessage\r\n\t\t\t\t, \"alertCode\" : alertCode\r\n\t\t\t\t, \"alertType\" : alertType\r\n\t\t\t});\r\n\t\t}\r\n\t\t\r\n\t\treturn isValidated;\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction deleteData(){\r\n\t\tif(!isSearchValidate()) { return false; }\r\n\t\tif(!isDeleteValidate()) { return false; }\r\n\t\t\r\n\t\tvar alertMessage = '");
      if (_jspx_meth_spring_005fmessage_005f5(_jspx_page_context))
        return;
      out.write("';\r\n\t\tvar alertCode = \"\";\r\n\t\tvar alertType = \"alert\";\r\n\t\tvar callbackFunction = function(){\r\n\t\t\tcrud = \"D\";\r\n\t\t\tsaveData();\r\n\t\t}\r\n\t\t\r\n\t\t$erp.confirmMessage({\r\n\t\t\t\"alertMessage\" : alertMessage\r\n\t\t\t, \"alertCode\" : alertCode\r\n\t\t\t, \"alertType\" : alertType\r\n\t\t\t, \"alertCallbackFn\" : callbackFunction\r\n\t\t});\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction saveData(){\r\n\t\tif(!isSaveValidate()) { \r\n\t\t\terpLayout.progressOff();\r\n\t\t\treturn false; \r\n\t\t}\t\t\r\n\t\r\n\t\tvar menu_cd = document.getElementById(\"txtMENU_CD\").value;\r\n\t\tvar menu_nm = document.getElementById(\"txtMENU_NM\").value;\r\n\t\tvar use_yn = cmbUSE_YN.getSelectedValue();\r\n\t\tvar folder_yn = cmbFOLDER_YN.getSelectedValue();\r\n\t\tvar upper_menu_cd = document.getElementById(\"txtUPPER_MENU_CD\").value;\r\n\t\tvar menu_ordr = document.getElementById(\"txtMENU_ORDR\").value;\r\n\t\t\r\n\t\t$.ajax({\r\n\t\t\turl : \"/common/system/menu/menuManagementCUD1.do\"\r\n\t\t\t,data : {\r\n\t\t\t\t\"CRUD\" : crud\r\n\t\t\t\t, \"MENU_CD\" : menu_cd\r\n\t\t\t\t, \"MENU_NM\" : menu_nm\r\n\t\t\t\t, \"USE_YN\" : use_yn\r\n\t\t\t\t, \"FOLDER_YN\" : folder_yn\r\n\t\t\t\t, \"UPPER_MENU_CD\" : upper_menu_cd\r\n\t\t\t\t, \"MENU_ORDR\" : menu_ordr\r\n\t\t\t}\r\n\t\t\t,method : \"POST\"\r\n\t\t\t,dataType : \"JSON\"\r\n\t\t\t,success : function(data){\r\n\t\t\t\terpLayout.progressOff();\r\n\t\t\t\tif(data.isError){\r\n\t\t\t\t\t$erp.ajaxErrorMessage(data);\r\n\t\t\t\t} else {\t\t\t\r\n\t\t\t\t\t$erp.alertSuccessMesage(onAfterSaveData);\t\t\t\t\t\r\n\t\t\t\t}\r\n\t\t\t}, error : function(jqXHR, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\terpLayout.progressOff();\r\n\t\t\t\t$erp.ajaxErrorHandler(jqXHR, textStatus, errorThrown);\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction onAfterSaveData(){\r\n\t\tsearchErpTree();\r\n\t}\r\n\t");
      out.write("\r\n\t\r\n\t");
      out.write("\t\r\n\t\r\n\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n\tfunction initDhtmlXCombo(){\r\n\t\tcmbUSE_YN = $erp.getDhtmlXCombo('cmbUSE_YN', 'USE_YN', ['YN_CD','YN'], 100, false);\r\n\t\tcmbFOLDER_YN = $erp.getDhtmlXCombo('cmbFOLDER_YN', 'FOLDER_YN', ['YN_CD','YN'], 100, false);\r\n\t}\r\n\t");
      out.write("\r\n</script>\r\n</head>\r\n<body>\r\n\t<div id=\"div_erp_tree\" class=\"div_tree_full_size\"></div>\t\r\n\t<div id=\"div_erp_ribbon\" class=\"div_ribbon_full_size\" style=\"display:none\"></div>\r\n\t<div id=\"div_erp_contents_wrapper\" class=\"div_common_contents_full_size\" style=\"display:none\">\r\n\t\t<table id=\"tb_erp_data\" class=\"tb_erp_common\">\r\n\t\t\t<colgroup>\r\n\t\t\t\t<col width=\"150px\" />\r\n\t\t\t\t<col width=\"*\" />\r\n\t\t\t</colgroup>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<td colspan=\"2\" class=\"td_subject\"><div id=\"div_data_info\" class=\"common_center\">메뉴 등록/수정 대기중</div></td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th><span class=\"span_essential\">*</span>메뉴코드</th>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<input type=\"text\" id=\"txtMENU_CD\" name=\"MENU_CD\" class=\"input_common input_readonly\" maxlength=\"20\" readonly=\"readonly\">\t\t\t\t\t\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th><span class=\"span_essential\">*</span>메뉴명</th>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<input type=\"text\" id=\"txtMENU_NM\" name=\"MENU_NM\" class=\"input_common\" maxlength=\"20\">\r\n\t\t\t\t\t\t<input type=\"hidden\" id=\"OLD_MENU_NM\">\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th>상위메뉴코드</th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<input type=\"text\" id=\"txtUPPER_MENU_CD\" name=\"UPPER_MENU_CD\" class=\"input_common input_readonly\" maxlength=\"20\" readonly=\"readonly\">\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th>상위메뉴명</th>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<input type=\"text\" id=\"txtUPPER_MENU_NM\" name=\"UPPER_MENU_NM\" class=\"input_common input_readonly\" maxlength=\"20\" readonly=\"readonly\">\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th><span class=\"span_essential\">*</span>메뉴순번</th>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<input type=\"text\" id=\"txtMENU_ORDR\" name=\"txtORDBY\" class=\"input_common input_number\" maxlength=\"20\">\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th><span class=\"span_essential\">*</span>사용여부</th>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<div id=\"cmbUSE_YN\"></div>\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr>\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<th><span class=\"span_essential\">*</span>폴더여부</th>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t<div id=\"cmbFOLDER_YN\"></div>\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n</body>\r\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f0_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f0.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuManagement.jsp(67,46) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f0.setCode("ribbon.add");
      int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
        if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
      _jspx_th_spring_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f1_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f1.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuManagement.jsp(68,51) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f1.setCode("ribbon.delete");
      int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
        if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
      _jspx_th_spring_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f2 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f2_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f2.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuManagement.jsp(69,49) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f2.setCode("ribbon.save");
      int[] _jspx_push_body_count_spring_005fmessage_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f2 = _jspx_th_spring_005fmessage_005f2.doStartTag();
        if (_jspx_th_spring_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f2);
      _jspx_th_spring_005fmessage_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f3 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f3_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f3.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuManagement.jsp(70,52) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f3.setCode("ribbon.excel");
      int[] _jspx_push_body_count_spring_005fmessage_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f3 = _jspx_th_spring_005fmessage_005f3.doStartTag();
        if (_jspx_th_spring_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f3);
      _jspx_th_spring_005fmessage_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f4 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f4_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f4.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f4.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuManagement.jsp(71,52) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f4.setCode("ribbon.print");
      int[] _jspx_push_body_count_spring_005fmessage_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f4 = _jspx_th_spring_005fmessage_005f4.doStartTag();
        if (_jspx_th_spring_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f4);
      _jspx_th_spring_005fmessage_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f4, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f5 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f5_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f5.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f5.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuManagement.jsp(335,22) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f5.setCode("alert.common.deleteData");
      int[] _jspx_push_body_count_spring_005fmessage_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f5 = _jspx_th_spring_005fmessage_005f5.doStartTag();
        if (_jspx_th_spring_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f5);
      _jspx_th_spring_005fmessage_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f5, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f5_reused);
    }
    return false;
  }
}
