/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2021-08-03 06:32:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.common.system.menu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menuByScreenManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.0.0.RELEASE.jar", Long.valueOf(1555919658000L));
    _jspx_dependants.put("jar:file:/C:/Winplus_SIS_Workspace8/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Winplus_SIS/WEB-INF/lib/spring-webmvc-5.0.0.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1506564196000L));
    _jspx_dependants.put("jar:file:/C:/Winplus_SIS_Workspace8/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Winplus_SIS/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Winplus_SIS_Workspace8/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Winplus_SIS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1555919670000L));
    _jspx_dependants.put("jar:file:/C:/Winplus_SIS_Workspace8/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Winplus_SIS/WEB-INF/lib/spring-webmvc-5.0.0.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1506564196000L));
    _jspx_dependants.put("/WEB-INF/jsp/common/include/taglib.jspf", Long.valueOf(1577410167197L));
    _jspx_dependants.put("jar:file:/C:/Winplus_SIS_Workspace8/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Winplus_SIS/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n\r\n\r\n");
      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.write("\r\n\r\n\r\n\r\n\r\n");
      out.write("\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/common/include/default_resources_header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/jsp/common/include/default_page_script_header.jsp", out, false);
      out.write("\r\n<script type=\"text/javascript\">\r\n\t");
      out.write("\r\n\tvar erpLayout;\r\n\tvar erpTree;\r\n\t\r\n\tvar erpLeftSubLayout;\r\n\tvar erpLeftRibbon;\r\n\tvar erpLeftGrid;\r\n\tvar erpLeftGridColumns;\r\n\tvar erpLeftGridDataProcessor;\r\n\t\r\n\tvar erpRightSubLayout;\r\n\tvar erpRightRibbon;\r\n\tvar erpRightGrid;\r\n\tvar erpRightGridColumns;\r\n\t\r\n\tvar currentErpTreeId;\r\n\tvar cmbUSE_YN;\r\n\tvar cmbCMMN_YN;\r\n\t\r\n\t$(document).ready(function(){\t\t\r\n\t\tinitErpLayout();\t\t\r\n\t\tinitErpTree();\r\n\t\t\r\n\t\tinitErpLeftSubLayout();\r\n\t\tinitErpLeftRibbon();\r\n\t\tinitErpLeftGrid();\r\n\t\t\r\n\t\tinitErpRightSubLayout();\r\n\t\tinitErpRightRibbon();\r\n\t\tinitErpRightGrid();\r\n\t\t\r\n\t\tinitDhtmlXCombo();\r\n\t\tsearchErpTree();\r\n\t\tsearchErpRightGrid();\r\n\t});\r\n\t\r\n\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n\tfunction initErpLayout(){\r\n\t\terpLayout = new dhtmlXLayoutObject({\r\n\t\t\tparent: document.body\r\n\t\t\t, skin : ERP_LAYOUT_CURRENT_SKINS\r\n\t\t\t, pattern: \"3W\"\r\n\t\t\t, cells: [\r\n\t\t\t\t{id: \"a\", text: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuDto.menu_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", header:true, width:220}\r\n\t\t\t\t, {id: \"b\", text: \"선택메뉴별화면목록\", header:true, width:795, fix_size : [false, true]}\r\n\t\t\t\t, {id: \"c\", text: \"전체화면목록\", header:true}\r\n\t\t\t]\t\t\r\n\t\t});\r\n\t\terpLayout.cells(\"a\").attachObject(\"div_erp_tree\");\r\n\t\terpLayout.cells(\"b\").attachObject(\"div_erp_left_sub_layout\");\r\n\t\terpLayout.cells(\"c\").attachObject(\"div_erp_right_sub_layout\");\r\n\t\t\r\n\t\t");
      out.write("\r\n\t\t$erp.setEventResizeDhtmlXLayout(erpLayout, function(names){\r\n\t\t\terpLeftSubLayout.setSizes();\r\n\t\t\terpRightSubLayout.setSizes();\r\n\t\t\terpLeftGrid.setSizes();\r\n\t\t\terpRightGrid.setSizes();\r\n\t\t});\r\n\t}\r\n\t");
      out.write("\r\n\t\r\n\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n\tfunction initErpTree(){\r\n\t\terpTree = new dhtmlXTreeObject({\r\n\t\t\tparent : \"div_erp_tree\"\r\n\t\t\t, skin : ERP_TREE_CURRENT_SKINS\t\t\t\r\n\t\t\t, image_path : ERP_TREE_CURRENT_IMAGE_PATH\r\n\t\t});\r\n\t\terpTree.attachEvent(\"onClick\", function(id){\r\n\t\t\tif(!$erp.isEmpty(id)){\r\n\t\t\t\t");
      out.write("\r\n\t\t\t\tif(id == \"#root\"){\r\n\t\t\t\t\tcurrentErpTreeId = null;\r\n\t\t\t\t\t$erp.clearInputInElement(\"tb_erp_data\");\r\n\t\t\t\t} else {\r\n\t\t\t\t\tcrud = null;\r\n\t\t\t\t\tcurrentErpTreeId = id;\r\n\t\t\t\t\tsearchErpLeftGrid();\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction searchErpTree(){\r\n\t\terpLayout.progressOn();\r\n\t\t\r\n\t\t$.ajax({\r\n\t\t\turl : \"/common/system/menu/menuByScreenManagementR1.do\"\r\n\t\t\t,data : {}\r\n\t\t\t,method : \"POST\"\r\n\t\t\t,dataType : \"JSON\"\r\n\t\t\t,success : function(data){\r\n\t\t\t\terpLayout.progressOff();\r\n\t\t\t\tif(data.isError){\r\n\t\t\t\t\t$erp.ajaxErrorMessage(data);\r\n\t\t\t\t} else {\t\t\t\r\n\t\t\t\t\tvar menuTreeMap = data.menuTreeMap;\r\n\t\t\t\t\tvar menuTreeDataList = menuTreeMap.item;\r\n\t\t\t\t\tif($erp.isEmpty(menuTreeDataList)){\r\n\t\t\t\t\t\t$erp.alertMessage({\r\n\t\t\t\t\t\t\t\"alertMessage\" : \"grid.noSearchData\"\r\n\t\t\t\t\t\t\t, \"alertCode\" : null\r\n\t\t\t\t\t\t\t, \"alertType\" : \"info\"\r\n\t\t\t\t\t\t});\r\n\t\t\t\t\t} else {\r\n\t\t\t\t\t\terpTree.deleteChildItems(0);\r\n\t\t\t\t\t\terpTree.parse(menuTreeMap, 'json');\r\n\t\t\t\t\t\tcurrentErpTreeId = null;\r\n\t\t\t\t\t\t$erp.clearInputInElement(\"tb_erp_data\");\r\n\t\t\t\t\t\terpTree.openAllItems(\"0\");\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t}, error : function(jqXHR, textStatus, errorThrown){\r\n\t\t\t\terpLayout.progressOff();\r\n\t\t\t\t$erp.ajaxErrorHandler(jqXHR, textStatus, errorThrown);\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n\t");
      out.write("\r\n\t\r\n\t");
      out.write("\t\r\n\t\r\n\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n\tfunction initErpLeftSubLayout(){\r\n\t\terpLeftSubLayout = new dhtmlXLayoutObject({\r\n\t\t\tparent: \"div_erp_left_sub_layout\"\r\n\t\t\t, skin : ERP_LAYOUT_CURRENT_SKINS\r\n\t\t\t, pattern: \"3E\"\r\n\t\t\t, cells: [\r\n\t\t\t\t{id: \"a\", text: \"\", header:false, width:200}\r\n\t\t\t\t, {id: \"b\", text: \"\", header:false, fix_size : [false, true]}\r\n\t\t\t\t, {id: \"c\", text: \"\", header:false, fix_size : [true, true]}\r\n\t\t\t]\t\t\r\n\t\t\t, fullScreen : true\r\n\t\t});\r\n\t\terpLeftSubLayout.cells(\"a\").attachObject(\"div_erp_left_contents_search\");\r\n\t\terpLeftSubLayout.cells(\"a\").setHeight(65);\r\n\t\terpLeftSubLayout.cells(\"b\").attachObject(\"div_erp_left_ribbon\");\r\n\t\terpLeftSubLayout.cells(\"b\").setHeight(ERP_LAYOUT_RIBBON_HEIGHT);\r\n\t\terpLeftSubLayout.cells(\"c\").attachObject(\"div_erp_left_grid\");\r\n\t\t\r\n\t\terpLeftSubLayout.setSeparatorSize(1, 0);\r\n\t}\t\r\n\t");
      out.write("\r\n\t\r\n\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n\tfunction initErpLeftRibbon(){\r\n\t\terpLeftRibbon = new dhtmlXRibbon({\r\n\t\t\tparent : \"div_erp_left_ribbon\"\r\n\t\t\t, skin : ERP_RIBBON_CURRENT_SKINS\r\n\t\t\t, icons_path : ERP_RIBBON_CURRENT_ICON_PATH\r\n\t\t\t, items : [\r\n\t\t\t\t{type : \"block\", mode : 'rows', list : [\r\n\t\t\t\t\t//{id : \"search_erpLeftGrid\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/search.gif\", imgdis : \"menu/search_dis.gif\", disable : true, unused : true}\r\n\t\t\t\t\t{id : \"add_erpLeftGrid\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/add.gif\", imgdis : \"menu/add_dis.gif\", disable : true}\r\n\t\t\t\t\t, {id : \"delete_erpLeftGrid\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/delete.gif\", imgdis : \"menu/delete_dis.gif\", disable : true}\r\n\t\t\t\t\t, {id : \"save_erpLeftGrid\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/save.gif\", imgdis : \"menu/save_dis.gif\", disable : true}\r\n\t\t\t\t\t//, {id : \"excel_erpLeftGrid\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f4(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/excel.gif\", imgdis : \"menu/excel_dis.gif\", disable : true, unused : true}\r\n\t\t\t\t\t//, {id : \"print_erpLeftGrid\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f5(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/print.gif\", imgdis : \"menu/print_dis.gif\", disable : true, unused : true}\t\r\n\t\t\t\t]}\t\t\t\t\t\t\t\r\n\t\t\t]\r\n\t\t});\r\n\t\t\r\n\t\terpLeftRibbon.attachEvent(\"onClick\", function(itemId, bId){\r\n\t\t\tif(itemId == \"search_erpLeftGrid\"){\r\n\t\t    \t\r\n\t\t    } else if (itemId == \"add_erpLeftGrid\"){\r\n\t\t    \taddErpLeftGrid();\r\n\t\t    } else if (itemId == \"delete_erpLeftGrid\"){\r\n\t\t    \tdeleteErpLeftGrid();\r\n\t\t    } else if (itemId == \"save_erpLeftGrid\"){\r\n\t\t    \tsaveErpLeftGrid();\r\n\t\t    } else if (itemId == \"excel_erpLeftGrid\"){\r\n\t\t    \t\r\n\t\t    } else if (itemId == \"print_erpLeftGrid\"){\r\n\t\t    \t\r\n\t\t    }\r\n\t\t});\r\n\t}\r\n\t");
      out.write("\r\n\t\r\n\t");
      out.write("\t\r\n\t");
      out.write("\t\r\n\tfunction initErpLeftGrid(){\r\n\t\terpLeftGridColumns = [\r\n\t\t\t{id : \"NO\", label:[\"NO\", \"#rspan\"], type: \"cntr\", width: \"30\", sort : \"int\", align : \"center\", isHidden : false, isEssential : false}\r\n\t\t\t, {id : \"CHECK\", label:[\"#master_checkbox\", \"#rspan\"], type: \"ch\", width: \"40\", sort : \"int\", align : \"center\", isHidden : false, isEssential : false, isDataColumn : false}\r\n\t\t\t, {id : \"MENU_CD\", label:[\"메뉴코드\", \"#rspan\"], type: \"ro\", width: \"60\", sort : \"str\", align : \"center\", isHidden : true, isEssential : false}\r\n\t\t\t, {id : \"SCRIN_CD\", label:[\"화면코드\", \"#text_filter\"], type: \"ro\", width: \"60\", sort : \"str\", align : \"center\", isHidden : false, isEssential : false}\r\n\t\t\t, {id : \"SCRIN_NM\", label:[\"화면명\", \"#text_filter\"], type: \"ro\", width: \"120\", sort : \"str\", align : \"left\", isHidden : false, isEssential : false}\r\n\t\t\t, {id : \"SCRIN_PATH\", label:[\"화면경로\", \"#text_filter\"], type: \"ro\", width: \"250\", sort : \"str\", align : \"left\", isHidden : false, isEssential : false}\r\n\t\t\t, {id : \"MAIN_YN\", label:[\"메인여부\", \"#select_filter\"], type: \"combo\", width: \"80\", sort : \"str\", align : \"center\", isHidden : false, isEssential : true, commonCode : [\"YN_CD\",\"YN\"]}\r\n");
      out.write("\t\t\t, {id : \"USE_YN\", label:[\"메뉴화면<br/>연동사용여부\", \"#select_filter\"], type: \"combo\", width: \"100\", sort : \"str\", align : \"center\", isHidden : false, isEssential : true, commonCode : [\"YN_CD\",\"YN\"]}\r\n\t\t\t, {id : \"SCRIN_USE_YN\", label:[\"화면사용여부상태\", \"#select_filter\"], type: \"ro\", width: \"100\", sort : \"str\", align : \"center\", isHidden : false, isEssential : false, commonCode : [\"YN_CD\",\"YN\"]}\t\t\t\r\n\t\t\t, {id : \"REG_PROGRM\", label:[\"등록프로그램\", \"#rspan\"], type: \"ro\", width: \"130\", sort : \"str\", align : \"left\", isHidden : false, isEssential : false}\r\n\t\t\t, {id : \"REG_ID\", label:[\"등록자\", \"#rspan\"], type: \"ro\", width: \"100\", sort : \"str\", align : \"center\", isHidden : false, isEssential : false}\r\n\t\t\t, {id : \"REG_DT\", label:[\"등록일시\", \"#rspan\"], type: \"ro\", width: \"140\", sort : \"str\", align : \"left\", isHidden : false, isEssential : false}\r\n\t\t\t, {id : \"UPD_PROGRM\", label:[\"수정프로그램\", \"#rspan\"], type: \"ro\", width: \"130\", sort : \"str\", align : \"left\", isHidden : false, isEssential : false}\r\n\t\t\t, {id : \"UPD_ID\", label:[\"수정자\", \"#rspan\"], type: \"ro\", width: \"100\", sort : \"str\", align : \"center\", isHidden : false, isEssential : false}\r\n");
      out.write("\t\t\t, {id : \"UPD_DT\", label:[\"수정일시\", \"#rspan\"], type: \"ro\", width: \"140\", sort : \"str\", align : \"left\", isHidden : false, isEssential : false}\r\n\t\t];\r\n\t\t\r\n\t\terpLeftGrid = new dhtmlXGridObject({\r\n\t\t\tparent: \"div_erp_left_grid\"\t\t\t\r\n\t\t\t, skin : ERP_GRID_CURRENT_SKINS\r\n\t\t\t, image_path : ERP_GRID_CURRENT_IMAGE_PATH\t\t\t\r\n\t\t\t, columns : erpLeftGridColumns\t\t\t\r\n\t\t});\t\t\r\n\t\terpLeftGrid.enableDistributedParsing(true, 100, 50);\r\n\t\t$erp.initGridCustomCell(erpLeftGrid);\r\n\t\t$erp.initGridComboCell(erpLeftGrid);\t\t\t\t\r\n\t\t$erp.attachDhtmlXGridFooterRowCount(erpLeftGrid, '");
      if (_jspx_meth_spring_005fmessage_005f6(_jspx_page_context))
        return;
      out.write("');\r\n\t\t\r\n\t\terpLeftGridDataProcessor = new dataProcessor();\r\n\t\terpLeftGridDataProcessor.init(erpLeftGrid);\r\n\t\terpLeftGridDataProcessor.setUpdateMode(\"off\");\r\n\t\t$erp.initGridDataColumns(erpLeftGrid);\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction isSearchErpLeftGridValidate(){\r\n\t\tvar isValidated = true;\r\n\t\tvar alertMessage = \"\";\r\n\t\tvar alertCode = \"\";\r\n\t\tvar alertType = \"error\";\r\n\t\t\r\n\t\tif($erp.isEmpty(currentErpTreeId)){\r\n\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.noSelectedData\";\r\n\t\t\talertCode = \"-1\";\r\n\t\t}\r\n\t\t\r\n\t\tif(!isValidated){\r\n\t\t\t$erp.alertMessage({\r\n\t\t\t\t\"alertMessage\" : alertMessage\r\n\t\t\t\t, \"alertCode\" : alertCode\r\n\t\t\t\t, \"alertType\" : alertType\r\n\t\t\t});\r\n\t\t}\r\n\t\t\r\n\t\treturn isValidated;\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction searchErpLeftGrid(){\r\n\t\tif(!isSearchErpLeftGridValidate()){\r\n\t\t\treturn;\r\n\t\t}\r\n\t\t\r\n\t\terpLayout.progressOn();\r\n\t\t\r\n\t\t$.ajax({\r\n\t\t\turl : \"/common/system/menu/menuByScreenManagementR2.do\"\r\n\t\t\t,data : {\r\n\t\t\t\t\"MENU_CD\" : currentErpTreeId\r\n\t\t\t}\r\n\t\t\t,method : \"POST\"\r\n\t\t\t,dataType : \"JSON\"\r\n\t\t\t,success : function(data){\r\n\t\t\t\terpLayout.progressOff();\r\n\t\t\t\tif(data.isError){\r\n\t\t\t\t\t$erp.ajaxErrorMessage(data);\r\n\t\t\t\t} else {\r\n\t\t\t\t\t$erp.clearDhtmlXGrid(erpLeftGrid);\r\n\t\t\t\t\t$erp.clearInputInElement(\"tb_erp_left_data\");\r\n\t\t\t\t\tvar dataMap = data.dataMap;\r\n\t\t\t\t\tif($erp.isEmpty(dataMap)){\r\n\t\t\t\t\t\t$erp.addDhtmlXGridNoDataPrintRow(\r\n\t\t\t\t\t\t\terpLeftGrid\r\n\t\t\t\t\t\t\t, '");
      if (_jspx_meth_spring_005fmessage_005f7(_jspx_page_context))
        return;
      out.write("'\r\n\t\t\t\t\t\t);\r\n\t\t\t\t\t} else {\t\t\t\t\t\t\r\n\t\t\t\t\t\t$erp.bindTextValue(dataMap, \"tb_erp_left_data\");\t\t\t\t\t\t\r\n\t\t\t\t\t\tvar gridDataList = data.gridDataList;\r\n\t\t\t\t\t\tif($erp.isEmpty(gridDataList)){\r\n\t\t\t\t\t\t\t$erp.addDhtmlXGridNoDataPrintRow(\r\n\t\t\t\t\t\t\t\t\terpLeftGrid\r\n\t\t\t\t\t\t\t\t\t, '");
      if (_jspx_meth_spring_005fmessage_005f8(_jspx_page_context))
        return;
      out.write("'\r\n\t\t\t\t\t\t\t);\r\n\t\t\t\t\t\t} else {\r\n\t\t\t\t\t\t\terpLeftGrid.parse(gridDataList, 'js');\r\n\t\t\t\t\t\t}\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t\t$erp.setDhtmlXGridFooterRowCount(erpLeftGrid);\r\n\t\t\t}, error : function(jqXHR, textStatus, errorThrown){\r\n\t\t\t\terpLayout.progressOff();\r\n\t\t\t\t$erp.ajaxErrorHandler(jqXHR, textStatus, errorThrown);\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction isAddErpLeftGridValidate(){\r\n\t\tvar isValidated = true;\r\n\t\tvar alertMessage = \"\";\r\n\t\tvar alertCode = \"\";\r\n\t\tvar alertType = \"error\";\r\n\t\t\r\n\t\tvar erpRightGridRowCount = erpRightGrid.getRowsNum();\r\n\t\t\r\n\t\tif($erp.isEmpty(currentErpTreeId)){\r\n\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.noSelectedData\";\r\n\t\t\talertCode = \"-1\";\r\n\t\t} else \tif(erpRightGridRowCount == 0){\r\n\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.noSelectedRow\";\r\n\t\t\talertCode = \"-2\";\r\n\t\t}\r\n\t\t\r\n\t\tif(!isValidated){\r\n\t\t\t$erp.alertMessage({\r\n\t\t\t\t\"alertMessage\" : alertMessage\r\n\t\t\t\t, \"alertCode\" : alertCode\r\n\t\t\t\t, \"alertType\" : alertType\r\n\t\t\t});\r\n\t\t}\r\n\t\t\r\n\t\treturn isValidated;\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction addErpLeftGrid(){\r\n\t\tif(!isAddErpLeftGridValidate()) { return false };\r\n\t\t\t\t\r\n\t\tvar erpRightGridRowCount = erpRightGrid.getRowsNum();\r\n\t\tfor(var i = 0; i < erpRightGridRowCount; i++){\r\n\t\t\tvar rightRId = erpRightGrid.getRowId(i);\r\n\t\t\tvar check = erpRightGrid.cells(rightRId, erpRightGrid.getColIndexById(\"CHECK\")).getValue();\r\n\t\t\tif(check == 1){\r\n\t\t\t\tvar scrin_cd = erpRightGrid.cells(rightRId, erpRightGrid.getColIndexById(\"SCRIN_CD\")).getValue();\r\n\t\t\t\tvar erpLeftGridRowCount = erpLeftGrid.getRowsNum();\r\n\t\t\t\tvar isAble = true;\r\n\t\t\t\tfor(var j = 0; j < erpLeftGridRowCount ; j++){\r\n\t\t\t\t\tvar leftRid = erpLeftGrid.getRowId(j);\r\n\t\t\t\t\tvar menuByScrin_cd = erpLeftGrid.cells(leftRid, erpLeftGrid.getColIndexById(\"SCRIN_CD\")).getValue();\r\n\t\t\t\t\tif(scrin_cd == menuByScrin_cd){\r\n\t\t\t\t\t\tisAble = false;\r\n\t\t\t\t\t\tbreak;\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t\tif(isAble === true){\r\n\t\t\t\t\tvar uid = erpLeftGrid.uid();\r\n\t\t\t\t\terpLeftGrid.addRow(uid);\r\n\t\t\t\t\t\r\n\t\t\t\t\tvar scrin_nm = erpRightGrid.cells(rightRId, erpRightGrid.getColIndexById(\"SCRIN_NM\")).getValue();\r\n");
      out.write("\t\t\t\t\tvar scrin_path = erpRightGrid.cells(rightRId, erpRightGrid.getColIndexById(\"SCRIN_PATH\")).getValue();\t\t\t\t\t\r\n\t\t\t\t\tvar main_yn = \"N\";\r\n\t\t\t\t\tvar use_yn = \"Y\";\r\n\t\t\t\t\tvar scrin_use_yn = erpRightGrid.cells(rightRId, erpRightGrid.getColIndexById(\"USE_YN\")).getValue();\r\n\t\t\t\t\t\r\n\t\t\t\t\terpLeftGrid.cells(uid, erpLeftGrid.getColIndexById(\"MENU_CD\")).setValue(currentErpTreeId);\r\n\t\t\t\t\terpLeftGrid.cells(uid, erpLeftGrid.getColIndexById(\"SCRIN_CD\")).setValue(scrin_cd);\r\n\t\t\t\t\terpLeftGrid.cells(uid, erpLeftGrid.getColIndexById(\"SCRIN_NM\")).setValue(scrin_nm);\r\n\t\t\t\t\terpLeftGrid.cells(uid, erpLeftGrid.getColIndexById(\"SCRIN_PATH\")).setValue(scrin_path);\r\n\t\t\t\t\terpLeftGrid.cells(uid, erpLeftGrid.getColIndexById(\"MAIN_YN\")).setValue(main_yn);\r\n\t\t\t\t\terpLeftGrid.cells(uid, erpLeftGrid.getColIndexById(\"USE_YN\")).setValue(use_yn);\r\n\t\t\t\t\terpLeftGrid.cells(uid, erpLeftGrid.getColIndexById(\"SCRIN_USE_YN\")).setValue(scrin_use_yn);\r\n\t\t\t\t}\r\n\t\t\t}\r\n\t\t}\r\n\t\t$erp.setDhtmlXGridFooterRowCount(erpLeftGrid);\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction deleteErpLeftGrid(){\r\n\t\tvar gridRowCount = erpLeftGrid.getRowsNum();\r\n\t\tvar isChecked = false;\r\n\t\t\r\n\t\tvar deleteRowIdArray = [];\r\n\t\tfor(var i = 0; i < gridRowCount; i++){\r\n\t\t\tvar rId = erpLeftGrid.getRowId(i);\r\n\t\t\tvar check = erpLeftGrid.cells(rId, erpLeftGrid.getColIndexById(\"CHECK\")).getValue();\r\n\t\t\tif(check == \"1\"){\r\n\t\t\t\tdeleteRowIdArray.push(rId);\r\n\t\t\t}\r\n\t\t}\r\n\t\t\r\n\t\tif(deleteRowIdArray.length == 0){\r\n\t\t\t$erp.alertMessage({\r\n\t\t\t\t\"alertMessage\" : \"error.common.noSelectedRow\"\r\n\t\t\t\t, \"alertCode\" : null\r\n\t\t\t\t, \"alertType\" : \"error\"\r\n\t\t\t});\r\n\t\t\treturn;\r\n\t\t}\r\n\t\t\r\n\t\tfor(var i = 0; i < deleteRowIdArray.length; i++){\r\n\t\t\terpLeftGrid.deleteRow(deleteRowIdArray[i]);\r\n\t\t}\r\n\t\t\r\n\t\t$erp.setDhtmlXGridFooterRowCount(erpLeftGrid);\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction isSaveErpLeftGridValidate(){\r\n\t\tvar isValidated = true;\r\n\t\tvar alertMessage = \"\";\r\n\t\tvar alertCode = \"\";\r\n\t\tvar alertType = \"error\";\r\n\t\t\r\n\t\tvar isMainYesCount = 0;\r\n\t\tvar erpLeftGridRowCount = erpLeftGrid.getRowsNum();\r\n\t\tfor(var i = 0; i < erpLeftGridRowCount ; i++){\r\n\t\t\tvar rId = erpLeftGrid.getRowId(i);\r\n\t\t\tvar tempStatus = erpLeftGrid.getDataProcessor().getState(rId);\r\n\t\t\tvar status = \"R\";\r\n\t\t\tif(tempStatus == \"inserted\"){\r\n\t\t\t\tstatus = \"C\";\r\n\t\t\t} else if (tempStatus == \"updated\"){\r\n\t\t\t\tstatus = \"U\";\r\n\t\t\t} else if (tempStatus == \"deleted\") {\r\n\t\t\t\tstatus = \"D\";\r\n\t\t\t}\r\n\t\t\t\r\n\t\t\tvar main_yn = erpLeftGrid.cells(rId, erpLeftGrid.getColIndexById(\"MAIN_YN\")).getValue();\r\n\t\t\t");
      out.write("\r\n\t\t\tif(status != \"D\" && main_yn == \"Y\"){\r\n\t\t\t\tisMainYesCount++;\r\n\t\t\t}\r\n\t\t}\r\n\t\t\r\n\t\tif(isMainYesCount > 1){\r\n\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.system.menu.menuByScreenManagement.main_yn.mustCountOne\";\r\n\t\t\talertCode = \"-1\";\r\n\t\t}\r\n\t\t\r\n\t\tif(!isValidated){\r\n\t\t\t$erp.alertMessage({\r\n\t\t\t\t\"alertMessage\" : alertMessage\r\n\t\t\t\t, \"alertCode\" : alertCode\r\n\t\t\t\t, \"alertType\" : alertType\r\n\t\t\t});\r\n\t\t}\r\n\t\t\r\n\t\treturn isValidated;\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction saveErpLeftGrid(){\r\n\t\tif(erpLeftGridDataProcessor.getSyncState()){\r\n\t\t\t$erp.alertMessage({\r\n\t\t\t\t\"alertMessage\" : \"error.common.noChanged\"\r\n\t\t\t\t, \"alertCode\" : null\r\n\t\t\t\t, \"alertType\" : \"error\"\r\n\t\t\t});\r\n\t\t\treturn false;\r\n\t\t}\r\n\t\t\r\n\t\tvar validResultMap = $erp.validDhtmlXGridEssentialData(erpLeftGrid);\r\n\t\tif(validResultMap.isError){\r\n\t\t\t$erp.alertMessage({\r\n\t\t\t\t\"alertMessage\" : validResultMap.errMessage\r\n\t\t\t\t, \"alertCode\" : validResultMap.errCode\r\n\t\t\t\t, \"alertType\" : \"error\"\r\n\t\t\t\t, \"alertMessageParam\" : validResultMap.errMessageParam\r\n\t\t\t});\r\n\t\t\treturn false;\r\n\t\t}\r\n\t\t\r\n\t\tif(!isSaveErpLeftGridValidate()){ return false; }\r\n\t\t\r\n\t\terpLayout.progressOn();\r\n\t\tvar paramData = $erp.serializeDhtmlXGridData(erpLeftGrid);\t\t\r\n\t\t$.ajax({\r\n\t\t\turl : \"/common/system/menu/menuByScreenManagementCUD1.do\"\r\n\t\t\t,data : paramData\r\n\t\t\t,method : \"POST\"\r\n\t\t\t,dataType : \"JSON\"\r\n\t\t\t,success : function(data){\r\n\t\t\t\terpLayout.progressOff();\r\n\t\t\t\tif(data.isError){\r\n\t\t\t\t\t$erp.ajaxErrorMessage(data);\r\n\t\t\t\t} else {\r\n\t\t\t\t\t$erp.alertSuccessMesage(onAfterSaveErpLeftGrid);\r\n");
      out.write("\t\t\t\t}\r\n\t\t\t}, error : function(jqXHR, textStatus, errorThrown){\r\n\t\t\t\terpLayout.progressOff();\r\n\t\t\t\t$erp.ajaxErrorHandler(jqXHR, textStatus, errorThrown);\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction onAfterSaveErpLeftGrid(){\r\n\t\tsearchErpLeftGrid();\r\n\t}\r\n\t");
      out.write("\r\n\t\r\n\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n\tfunction initErpRightSubLayout(){\r\n\t\terpRightSubLayout = new dhtmlXLayoutObject({\r\n\t\t\tparent: \"div_erp_right_sub_layout\"\r\n\t\t\t, skin : ERP_LAYOUT_CURRENT_SKINS\r\n\t\t\t, pattern: \"3E\"\r\n\t\t\t, cells: [\r\n\t\t\t\t{id: \"a\", text: \"\", header:false, width:200}\r\n\t\t\t\t, {id: \"b\", text: \"\", header:false, fix_size : [false, true]}\r\n\t\t\t\t, {id: \"c\", text: \"\", header:false, fix_size : [true, true]}\r\n\t\t\t]\t\t\r\n\t\t\t, fullScreen : true\r\n\t\t});\r\n\t\terpRightSubLayout.cells(\"a\").attachObject(\"div_erp_right_contents_search\");\r\n\t\terpRightSubLayout.cells(\"a\").setHeight(65);\r\n\t\terpRightSubLayout.cells(\"b\").attachObject(\"div_erp_right_ribbon\");\r\n\t\terpRightSubLayout.cells(\"b\").setHeight(ERP_LAYOUT_RIBBON_HEIGHT);\r\n\t\terpRightSubLayout.cells(\"c\").attachObject(\"div_erp_right_grid\");\r\n\t\t\r\n\t\terpRightSubLayout.setSeparatorSize(1, 0);\r\n\t}\t\r\n\t");
      out.write("\r\n\t\r\n\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n\tfunction initErpRightRibbon(){\r\n\t\terpRightRibbon = new dhtmlXRibbon({\r\n\t\t\tparent : \"div_erp_right_ribbon\"\r\n\t\t\t, skin : ERP_RIBBON_CURRENT_SKINS\r\n\t\t\t, icons_path : ERP_RIBBON_CURRENT_ICON_PATH\r\n\t\t\t, items : [\r\n\t\t\t\t{type : \"block\", mode : 'rows', list : [\r\n\t\t\t\t\t{id : \"search_erpRightGrid\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f9(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/search.gif\", imgdis : \"menu/search_dis.gif\", disable : true}\r\n\t\t\t\t\t//, {id : \"add_erpRightGrid\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f10(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/add.gif\", imgdis : \"menu/add_dis.gif\", disable : true, unused : true}\r\n\t\t\t\t\t//, {id : \"delete_erpRightGrid\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f11(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/delete.gif\", imgdis : \"menu/delete_dis.gif\", disable : true, unused : true}\r\n\t\t\t\t\t//, {id : \"save_erpRightGrid\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f12(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/save.gif\", imgdis : \"menu/save_dis.gif\", disable : true, unused : true}\r\n\t\t\t\t\t//, {id : \"excel_erpRightGrid\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f13(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/excel.gif\", imgdis : \"menu/excel_dis.gif\", disable : true, unused : true}\r\n\t\t\t\t\t//, {id : \"print_erpRightGrid\", type : \"button\", text:'");
      if (_jspx_meth_spring_005fmessage_005f14(_jspx_page_context))
        return;
      out.write("', isbig : false, img : \"menu/print.gif\", imgdis : \"menu/print_dis.gif\", disable : true, unused : true}\t\r\n\t\t\t\t]}\t\t\t\t\t\t\t\r\n\t\t\t]\r\n\t\t});\r\n\t\t\r\n\t\terpRightRibbon.attachEvent(\"onClick\", function(itemId, bId){\r\n\t\t\tif(itemId == \"search_erpRightGrid\"){\r\n\t\t    \tsearchErpRightGrid();\r\n\t\t    } else if (itemId == \"add_erpRightGrid\"){\r\n\t\t    \t\r\n\t\t    } else if (itemId == \"delete_erpRightGrid\"){\r\n\t\t    \t\r\n\t\t    } else if (itemId == \"save_erpRightGrid\"){\r\n\t\t    \t\r\n\t\t    } else if (itemId == \"excel_erpRightGrid\"){\r\n\t\t    \t\r\n\t\t    } else if (itemId == \"print_erpRightGrid\"){\r\n\t\t    \t\r\n\t\t    }\r\n\t\t});\r\n\t}\r\n\t");
      out.write("\r\n\t\r\n\t");
      out.write("\t\r\n\t");
      out.write("\t\r\n\tfunction initErpRightGrid(){\r\n\t\terpRightGridColumns = [\r\n\t\t\t{id : \"NO\", label:[\"NO\", \"#rspan\"], type: \"cntr\", width: \"30\", sort : \"int\", align : \"center\", isHidden : false, isEssential : false}\r\n\t\t\t, {id : \"CHECK\", label:[\"#master_checkbox\", \"#rspan\"], type: \"ch\", width: \"40\", sort : \"int\", align : \"center\", isHidden : false, isEssential : false, isDataColumn : false}\r\n\t\t\t, {id : \"SCRIN_CD\", label:[\"화면코드\", \"#text_filter\"], type: \"ro\", width: \"60\", sort : \"str\", align : \"center\", isHidden : false, isEssential : false}\r\n\t\t\t, {id : \"SCRIN_NM\", label:[\"화면명\", \"#text_filter\"], type: \"ro\", width: \"120\", sort : \"str\", align : \"left\", isHidden : false, isEssential : false}\r\n\t\t\t, {id : \"SCRIN_PATH\", label:[\"화면경로\", \"#text_filter\"], type: \"ro\", width: \"250\", sort : \"str\", align : \"left\", isHidden : false, isEssential : false}\r\n\t\t\t, {id : \"USE_YN\", label:[\"사용여부\", \"#text_filter\"], type: \"ro\", width: \"80\", sort : \"str\", align : \"center\", isHidden : false, isEssential : false}\r\n\t\t\t, {id : \"CMMN_YN\", label:[\"공통여부\", \"#text_filter\"], type: \"ro\", width: \"80\", sort : \"str\", align : \"center\", isHidden : false, isEssential : false}\r\n");
      out.write("\t\t];\r\n\t\t\r\n\t\terpRightGrid = new dhtmlXGridObject({\r\n\t\t\tparent: \"div_erp_right_grid\"\t\t\t\r\n\t\t\t, skin : ERP_GRID_CURRENT_SKINS\r\n\t\t\t, image_path : ERP_GRID_CURRENT_IMAGE_PATH\t\t\t\r\n\t\t\t, columns : erpRightGridColumns\t\t\t\r\n\t\t});\t\t\r\n\t\terpRightGrid.enableDistributedParsing(true, 100, 50);\r\n\t\t$erp.initGridCustomCell(erpRightGrid);\r\n\t\t$erp.initGridComboCell(erpRightGrid);\t\t\t\t\r\n\t\t$erp.attachDhtmlXGridFooterRowCount(erpRightGrid, '");
      if (_jspx_meth_spring_005fmessage_005f15(_jspx_page_context))
        return;
      out.write("');\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction isSearchErpRightGridValidate(){\r\n\t\tvar isValidated = true;\t\t\r\n\t\tvar alertMessage = \"\";\r\n\t\tvar alertCode = \"\";\r\n\t\tvar alertType = \"error\";\r\n\t\t\r\n\t\tvar scrin_cd = document.getElementById(\"txtSCRIN_CD\").value;\r\n\t\t\r\n\t\tif($erp.isLengthOver(scrin_cd, 50)){\r\n\t\t\tisValidated = false;\r\n\t\t\talertMessage = \"error.common.system.menu.scrin_nm.length50Over\";\r\n\t\t\talertCode = \"-1\";\r\n\t\t} \t\t\r\n\t\t\r\n\t\tif(!isValidated){\r\n\t\t\t$erp.alertMessage({\r\n\t\t\t\t\"alertMessage\" : alertMessage\r\n\t\t\t\t, \"alertCode\" : alertCode\r\n\t\t\t\t, \"alertType\" : alertType\r\n\t\t\t});\r\n\t\t}\r\n\t\t\r\n\t\treturn isValidated;\r\n\t}\r\n\t\r\n\t");
      out.write("\r\n\tfunction searchErpRightGrid(){\r\n\t\tif(!isSearchErpRightGridValidate()){\r\n\t\t\treturn;\r\n\t\t}\r\n\t\t\r\n\t\terpLayout.progressOn();\r\n\t\t\r\n\t\tvar scrin_cd = document.getElementById(\"txtSCRIN_CD\").value;\r\n\t\tvar use_yn = cmbUSE_YN.getSelectedValue();\r\n\t\tvar cmmn_yn = cmbCMMN_YN.getSelectedValue();\r\n\t\t\r\n\t\t$.ajax({\r\n\t\t\turl : \"/common/system/menu/menuByScreenManagementR3.do\"\r\n\t\t\t,data : {\r\n\t\t\t\t\"SCRIN_CD\" : scrin_cd\r\n\t\t\t\t, \"USE_YN\" : use_yn\r\n\t\t\t\t, \"CMMN_YN\" : cmmn_yn\r\n\t\t\t}\r\n\t\t\t,method : \"POST\"\r\n\t\t\t,dataType : \"JSON\"\r\n\t\t\t,success : function(data){\r\n\t\t\t\terpLayout.progressOff();\r\n\t\t\t\tif(data.isError){\r\n\t\t\t\t\t$erp.ajaxErrorMessage(data);\r\n\t\t\t\t} else {\r\n\t\t\t\t\t$erp.clearDhtmlXGrid(erpRightGrid);\r\n\t\t\t\t\tvar gridDataList = data.gridDataList;\r\n\t\t\t\t\tif($erp.isEmpty(gridDataList)){\r\n\t\t\t\t\t\t$erp.addDhtmlXGridNoDataPrintRow(\r\n\t\t\t\t\t\t\terpRightGrid\r\n\t\t\t\t\t\t\t, '");
      if (_jspx_meth_spring_005fmessage_005f16(_jspx_page_context))
        return;
      out.write("'\r\n\t\t\t\t\t\t);\r\n\t\t\t\t\t} else {\r\n\t\t\t\t\t\terpRightGrid.parse(gridDataList, 'js');\r\n\t\t\t\t\t}\r\n\t\t\t\t}\r\n\t\t\t\t$erp.setDhtmlXGridFooterRowCount(erpRightGrid);\r\n\t\t\t}, error : function(jqXHR, textStatus, errorThrown){\r\n\t\t\t\terpLayout.progressOff();\r\n\t\t\t\t$erp.ajaxErrorHandler(jqXHR, textStatus, errorThrown);\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n\t");
      out.write("\r\n\t\r\n\t");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n\tfunction initDhtmlXCombo(){\r\n\t\tcmbUSE_YN = $erp.getDhtmlXCombo('cmbUSE_YN', 'USE_YN', ['YN_CD','YN'], 100, true);\r\n\t\tcmbCMMN_YN = $erp.getDhtmlXCombo('cmbCMMN_YN', 'CMMN_YN', ['YN_CD','YN'], 100, true);\r\n\t}\r\n\t");
      out.write("\r\n</script>\r\n</head>\r\n<body>\r\n\t<div id=\"div_erp_tree\" class=\"div_tree_full_size\"></div>\t\t\r\n\t\r\n\t<div id=\"div_erp_left_sub_layout\" class=\"div_layout_full_size div_sub_layout\" style=\"display:none\"></div>\r\n\t<div id=\"div_erp_left_ribbon\" class=\"div_ribbon_full_size\" style=\"display:none\"></div>\r\n\t<div id=\"div_erp_left_grid\" class=\"div_grid_full_size\" style=\"display:none\"></div>\r\n\t\r\n\t<div id=\"div_erp_right_sub_layout\" class=\"div_layout_full_size div_sub_layout\" style=\"display:none\"></div>\r\n\t<div id=\"div_erp_right_ribbon\" class=\"div_ribbon_full_size\" style=\"display:none\"></div>\t\r\n\t<div id=\"div_erp_right_grid\" class=\"div_grid_full_size\" style=\"display:none\"></div>\t\r\n\t\r\n\t<div id=\"div_erp_left_contents_search\" class=\"div_erp_contents_search\" style=\"display:none\">\r\n\t\t<table id=\"tb_erp_left_data\" class=\"table_search\">\r\n\t\t\t<colgroup>\r\n\t\t\t\t<col width=\"150px\">\r\n\t\t\t\t<col width=\"150px\">\r\n\t\t\t\t<col width=\"150px\">\r\n\t\t\t\t<col width=\"*\">\t\t\t\t\r\n\t\t\t</colgroup>\r\n\t\t\t<tr>\r\n\t\t\t\t<th>선택 메뉴코드</th>\r\n\t\t\t\t<td><input type=\"text\" id=\"txtMENU_CD\" name=\"MENU_CD\" class=\"input_common input_readonly\" maxlength=\"20\" readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t\t<th>선택 메뉴명</th>\r\n\t\t\t\t<td><input type=\"text\" id=\"txtMENU_NM\" name=\"MENU_NM\" class=\"input_common input_readonly\" maxlength=\"50\" readonly=\"readonly\"></td>\t\t\t\t\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th>선택 메뉴 메인 화면코드</th>\r\n\t\t\t\t<td><input type=\"text\" id=\"txtMAIN_SCRIN_CD\" name=\"MAIN_SCRIN_CD\" class=\"input_common input_readonly\" maxlength=\"20\" readonly=\"readonly\"></td>\r\n\t\t\t\t<th>선택 메뉴 메인 화면명</th>\r\n\t\t\t\t<td><input type=\"text\" id=\"txtMAIN_SCRIN_NM\" name=\"MAIN_SCRIN_NM\" class=\"input_common input_readonly\" maxlength=\"50\" readonly=\"readonly\"></td>\t\t\t\t\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n\t<div id=\"div_erp_right_contents_search\" class=\"div_erp_contents_search\" style=\"display:none\">\r\n\t\t<table class=\"table_search\">\r\n\t\t\t<colgroup>\r\n\t\t\t\t<col width=\"150px\">\r\n\t\t\t\t<col width=\"150px\">\r\n\t\t\t\t<col width=\"150px\">\r\n\t\t\t\t<col width=\"*\">\t\t\r\n\t\t\t</colgroup>\r\n\t\t\t<tr>\r\n\t\t\t\t<th>화면코드/화면명</th>\r\n\t\t\t\t<td colspan=\"3\"><input type=\"text\" id=\"txtSCRIN_CD\" name=\"SCRIN_CD\" class=\"input_common\" maxlength=\"505\" onkeydown=\"$erp.onEnterKeyDown(event, searchErpRightGrid);\"></td>\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<th>사용여부</th>\r\n\t\t\t\t<td><div id=\"cmbUSE_YN\"></div></td>\r\n\t\t\t\t<th>공통여부</th>\r\n\t\t\t\t<td><div id=\"cmbCMMN_YN\"></div></td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t</div>\r\n</body>\r\n</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f0_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f0.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(192,58) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f0.setCode("ribbon.search");
      int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
        if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
      _jspx_th_spring_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f1_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f1.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(193,53) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f1.setCode("ribbon.add");
      int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
        if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
      _jspx_th_spring_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f2 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f2_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f2.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(194,58) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f2.setCode("ribbon.delete");
      int[] _jspx_push_body_count_spring_005fmessage_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f2 = _jspx_th_spring_005fmessage_005f2.doStartTag();
        if (_jspx_th_spring_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f2);
      _jspx_th_spring_005fmessage_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f3 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f3_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f3.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(195,56) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f3.setCode("ribbon.save");
      int[] _jspx_push_body_count_spring_005fmessage_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f3 = _jspx_th_spring_005fmessage_005f3.doStartTag();
        if (_jspx_th_spring_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f3);
      _jspx_th_spring_005fmessage_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f4 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f4_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f4.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f4.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(196,59) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f4.setCode("ribbon.excel");
      int[] _jspx_push_body_count_spring_005fmessage_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f4 = _jspx_th_spring_005fmessage_005f4.doStartTag();
        if (_jspx_th_spring_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f4);
      _jspx_th_spring_005fmessage_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f4, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f5 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f5_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f5.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f5.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(197,59) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f5.setCode("ribbon.print");
      int[] _jspx_push_body_count_spring_005fmessage_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f5 = _jspx_th_spring_005fmessage_005f5.doStartTag();
        if (_jspx_th_spring_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f5);
      _jspx_th_spring_005fmessage_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f5, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f6 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f6_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f6.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f6.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(250,52) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f6.setCode("grid.allRowCount");
      int[] _jspx_push_body_count_spring_005fmessage_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f6 = _jspx_th_spring_005fmessage_005f6.doStartTag();
        if (_jspx_th_spring_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f6.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f6);
      _jspx_th_spring_005fmessage_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f6, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f7 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f7_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f7.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f7.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(308,10) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f7.setCode("grid.noSearchData");
      int[] _jspx_push_body_count_spring_005fmessage_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f7 = _jspx_th_spring_005fmessage_005f7.doStartTag();
        if (_jspx_th_spring_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f7.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f7);
      _jspx_th_spring_005fmessage_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f7, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f8 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f8_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f8.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f8.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(316,12) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f8.setCode("grid.noSearchData");
      int[] _jspx_push_body_count_spring_005fmessage_005f8 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f8 = _jspx_th_spring_005fmessage_005f8.doStartTag();
        if (_jspx_th_spring_005fmessage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f8[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f8.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f8.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f8);
      _jspx_th_spring_005fmessage_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f8, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f9 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f9_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f9.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f9.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(568,57) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f9.setCode("ribbon.search");
      int[] _jspx_push_body_count_spring_005fmessage_005f9 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f9 = _jspx_th_spring_005fmessage_005f9.doStartTag();
        if (_jspx_th_spring_005fmessage_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f9[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f9.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f9.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f9);
      _jspx_th_spring_005fmessage_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f9, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f10 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f10_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f10.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f10.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(569,58) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f10.setCode("ribbon.add");
      int[] _jspx_push_body_count_spring_005fmessage_005f10 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f10 = _jspx_th_spring_005fmessage_005f10.doStartTag();
        if (_jspx_th_spring_005fmessage_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f10[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f10.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f10.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f10);
      _jspx_th_spring_005fmessage_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f10, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f11 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f11_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f11.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f11.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(570,61) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f11.setCode("ribbon.delete");
      int[] _jspx_push_body_count_spring_005fmessage_005f11 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f11 = _jspx_th_spring_005fmessage_005f11.doStartTag();
        if (_jspx_th_spring_005fmessage_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f11[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f11.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f11.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f11);
      _jspx_th_spring_005fmessage_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f11, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f12 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f12_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f12.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f12.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(571,59) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f12.setCode("ribbon.save");
      int[] _jspx_push_body_count_spring_005fmessage_005f12 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f12 = _jspx_th_spring_005fmessage_005f12.doStartTag();
        if (_jspx_th_spring_005fmessage_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f12[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f12.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f12.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f12);
      _jspx_th_spring_005fmessage_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f12, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f13 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f13_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f13.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f13.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(572,60) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f13.setCode("ribbon.excel");
      int[] _jspx_push_body_count_spring_005fmessage_005f13 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f13 = _jspx_th_spring_005fmessage_005f13.doStartTag();
        if (_jspx_th_spring_005fmessage_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f13[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f13.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f13.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f13);
      _jspx_th_spring_005fmessage_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f13, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f13_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f14 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f14_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f14.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f14.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(573,60) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f14.setCode("ribbon.print");
      int[] _jspx_push_body_count_spring_005fmessage_005f14 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f14 = _jspx_th_spring_005fmessage_005f14.doStartTag();
        if (_jspx_th_spring_005fmessage_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f14[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f14.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f14.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f14);
      _jspx_th_spring_005fmessage_005f14_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f14, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f14_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f15 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f15_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f15.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f15.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(618,53) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f15.setCode("grid.allRowCount");
      int[] _jspx_push_body_count_spring_005fmessage_005f15 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f15 = _jspx_th_spring_005fmessage_005f15.doStartTag();
        if (_jspx_th_spring_005fmessage_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f15[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f15.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f15.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f15);
      _jspx_th_spring_005fmessage_005f15_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f15, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f15_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f16 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f16_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f16.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f16.setParent(null);
      // /WEB-INF/jsp/common/system/menu/menuByScreenManagement.jsp(678,10) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f16.setCode("grid.noSearchData");
      int[] _jspx_push_body_count_spring_005fmessage_005f16 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f16 = _jspx_th_spring_005fmessage_005f16.doStartTag();
        if (_jspx_th_spring_005fmessage_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f16[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f16.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f16.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f16);
      _jspx_th_spring_005fmessage_005f16_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f16, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f16_reused);
    }
    return false;
  }
}
